# Generated by Django 4.2.8 on 2024-03-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_listed_offer',
            field=models.BooleanField(default=True),
        ),
    ]
