# Generated by Django 4.2.8 on 2024-03-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0090_alter_profile_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(
                default="<function uuid4 at 0x00000167EBA41DC0>", max_length=200
            ),
        ),
    ]
