# Generated by Django 4.2.8 on 2024-02-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_remove_cart_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
